[project]
name = "fuzzmap"
version = "0.1.0"
description = "Asistente inteligente para estudio universitario con árboles AVL, lógica difusa y PLN"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "streamlit",
    "scikit-fuzzy",
    "spacy",
    "nltk",
    "pdfminer.six",
    "PyPDF2",
    "networkx",
    "pandas",
    "numpy",
    "altair",
    "matplotlib",
    "jupyter"
]

[tool.jupyter]
kernel_name = "python3"
display_name = "Python (FuzzMap)"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"